// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gameStore.Api.Data;

#nullable disable

namespace gameStore.Api.Data.Migrations
{
    [DbContext(typeof(GameStoreContext))]
    [Migration("20240522213022_SeedGenres")]
    partial class SeedGenres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("gameStore.Api.Entities.Game", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenreID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("GenreID");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            GenreID = 1,
                            Name = "Halo",
                            Price = 59.99m,
                            ReleaseDate = new DateOnly(2001, 11, 15)
                        },
                        new
                        {
                            ID = 2,
                            GenreID = 3,
                            Name = "The Witcher 3",
                            Price = 39.99m,
                            ReleaseDate = new DateOnly(2015, 5, 19)
                        },
                        new
                        {
                            ID = 3,
                            GenreID = 4,
                            Name = "The Sims 4",
                            Price = 29.99m,
                            ReleaseDate = new DateOnly(2014, 9, 2)
                        },
                        new
                        {
                            ID = 4,
                            GenreID = 5,
                            Name = "Civilization VI",
                            Price = 59.99m,
                            ReleaseDate = new DateOnly(2016, 10, 21)
                        });
                });

            modelBuilder.Entity("gameStore.Api.Entities.Genre", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Action"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Adventure"
                        },
                        new
                        {
                            ID = 3,
                            Name = "RPG"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Simulation"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Strategy"
                        });
                });

            modelBuilder.Entity("gameStore.Api.Entities.Game", b =>
                {
                    b.HasOne("gameStore.Api.Entities.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });
#pragma warning restore 612, 618
        }
    }
}
